// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4CqxQ78PwXNv1i02hjoOuWFHLH9aaZ6M',
    appId: '1:890923806628:web:e573743fad7a8e74b91b31',
    messagingSenderId: '890923806628',
    projectId: 'notes-app-nafisa',
    authDomain: 'notes-app-nafisa.firebaseapp.com',
    storageBucket: 'notes-app-nafisa.firebasestorage.app',
    measurementId: 'G-CLEMHYLQPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XzTjyvyybqNareyOOx3MK2ghKDYfktI',
    appId: '1:890923806628:android:a06f72730bfb7e06b91b31',
    messagingSenderId: '890923806628',
    projectId: 'notes-app-nafisa',
    storageBucket: 'notes-app-nafisa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Hppgc9zw4EbsziR1FEVJGx7_cBxiU5M',
    appId: '1:890923806628:ios:9ffa33577dc9e019b91b31',
    messagingSenderId: '890923806628',
    projectId: 'notes-app-nafisa',
    storageBucket: 'notes-app-nafisa.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Hppgc9zw4EbsziR1FEVJGx7_cBxiU5M',
    appId: '1:890923806628:ios:9ffa33577dc9e019b91b31',
    messagingSenderId: '890923806628',
    projectId: 'notes-app-nafisa',
    storageBucket: 'notes-app-nafisa.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4CqxQ78PwXNv1i02hjoOuWFHLH9aaZ6M',
    appId: '1:890923806628:web:97a0b0d7252a5cbcb91b31',
    messagingSenderId: '890923806628',
    projectId: 'notes-app-nafisa',
    authDomain: 'notes-app-nafisa.firebaseapp.com',
    storageBucket: 'notes-app-nafisa.firebasestorage.app',
    measurementId: 'G-QSJ24E7NHC',
  );
}
